function nonHTcfg = phy_config(waveCfg)
    % --- Configure PHY layer ---
    nonHTcfg = wlanNonHTConfig( ...
        'ChannelBandwidth', waveCfg.BW, ...
        'MCS', waveCfg.MCS, ...
        'NumTransmitAntennas', 1, ...
        'PSDULength', waveCfg.lengthMPDU);
end
